        SUBROUTINE soil(NA,ND,NT,NE,NAX,NDX,NTX,NEX ,&                                                                                                                                                                                                           
         NHW,NHE,NVN,NVS)                                                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
  !     THIS IS THE MAIN SUBROUTINE FROM WHICH ALL OTHERS ARE CALLED                                                                                                                                                                                             
  !                                                                                                                                                                                                                                                              
        include "parameters.h"                                                                                                                                                                                                                                   
        include "filec.h"                                                                                                                                                                                                                                        
        include "files.h"                                                                                                                                                                                                                                        
        include "blkc.h"                                                                                                                                                                                                                                         
        CHARACTER*16 DATA(30) DATAC(30,250,250),DATAP(05,JY,JX) ,&                                                                                                                                                                                               
         DATAM(05,JY,JX),DATAX(05),DATAY(05),DATAZ(05,JY,JX) ,&                                                                                                                                                                                                  
         OUTS(10),OUTP(10),OUTFILS(10,JY,JX),OUTFILP(10,05,JY,JX)                                                                                                                                                                                                
        CHARACTER*3 CHOICE(102 20)                                                                                                                                                                                                                               
        CHARACTER*8 CDATE                                                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
  !     READ INPUT DATA FOR SITE  SOILS AND MANAGEMENT IN 'READS'                                                                                                                                                                                                
  !     AND SET UP OUTPUT AND CHECKPOINT FILES IN 'FOUTS'                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
        IF(IGO.EQ.0)THEN                                                                                                                                                                                                                                         
  !      WRITE(* 333)'READI'                                                                                                                                                                                                                                     
        CALL READI(NA ND,NT,NE,NAX,NDX,NTX,NEX,NF,NFX,NTZ ,&                                                                                                                                                                                                     
         NTZX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                                   
        ENDIF                                                                                                                                                                                                                                                    
  !      WRITE(* 333)'READS'                                                                                                                                                                                                                                     
        CALL READS(NA ND,NT,NE,NAX,NDX,NTX,NEX,NF,NFX,NTZ ,&                                                                                                                                                                                                     
         NTZX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                                   
  !      WRITE(* 333)'FOUTS'                                                                                                                                                                                                                                     
        CALL FOUTS(NT NE,NAX,NDX,NTX,NEX,NF,NFX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                 
  !                                                                                                                                                                                                                                                              
  !     INITIALIZE ALL SOIL VARIABLES IN 'STARTS'                                                                                                                                                                                                                
  !                                                                                                                                                                                                                                                              
        IF((DATA(20).EQ.'YES'.AND.IGO.EQ.0).OR.IDAYR.NE.IOLD)THEN                                                                                                                                                                                                
  !      WRITE(* 333)'STARTS'                                                                                                                                                                                                                                    
        CALL STARTS(NHW NHE,NVN,NVS)                                                                                                                                                                                                                             
  !                                                                                                                                                                                                                                                              
  !     RECOVER VALUES OF ALL SOIL STATE VARIABLES FROM EARLIER RUN                                                                                                                                                                                              
  !     IN 'ROUTS' IF NEEDED                                                                                                                                                                                                                                     
  !                                                                                                                                                                                                                                                              
        IF(DATA(20).EQ.'YES')THEN                                                                                                                                                                                                                                
        IF((IDAYR.GE.IRUN.AND.IYRR.EQ.IDATA(9)) &                                                                                                                                                                                                                
        .OR.IYRR.GT.IDATA(9))THEN                                                                                                                                                                                                                                
  !      WRITE(* 333)'ROUTS'                                                                                                                                                                                                                                     
        CALL ROUTS(NHW NHE,NVN,NVS)                                                                                                                                                                                                                              
        ENDIF                                                                                                                                                                                                                                                    
        ENDIF                                                                                                                                                                                                                                                    
        ENDIF                                                                                                                                                                                                                                                    
  !                                                                                                                                                                                                                                                              
  !     RECOVER PLANT SPECIES DISTRIBUTION IN 'ROUTQ'                                                                                                                                                                                                            
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'ROUTQ'                                                                                                                                                                                                                                     
        CALL ROUTQ(NT NE,NAX,NDX,NTX,NEX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
  !     READ INPUT DATA FOR PLANT SPECIES AND MANAGEMENT IN 'READQ'                                                                                                                                                                                              
  !     AND SET UP OUTPUT AND CHECKPOINT FILES IN 'FOUTP'                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'READQ'                                                                                                                                                                                                                                     
        CALL READQ(NA ND,NT,NE,NAX,NDX,NTX,NEX,NF,NFX,NTZ ,&                                                                                                                                                                                                     
         NTZX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                                   
  !      WRITE(* 333)'FOUTP'                                                                                                                                                                                                                                     
        CALL FOUTP(NT NE,NAX,NDX,NTX,NEX,NF,NFX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                 
  !                                                                                                                                                                                                                                                              
  !     INITIALIZE ALL PLANT VARIABLES IN 'STARTQ'                                                                                                                                                                                                               
  !                                                                                                                                                                                                                                                              
        IF((DATA(20).EQ.'YES'.AND.IGO.EQ.0).OR.IDAYR.NE.IOLD)THEN                                                                                                                                                                                                
  !      WRITE(* 333)'STARTQ'                                                                                                                                                                                                                                    
        CALL STARTQ(NHW NHE,NVN,NVS)                                                                                                                                                                                                                             
  !                                                                                                                                                                                                                                                              
  !     RECOVER VALUES OF ALL PLANT STATE VARIABLES FROM EARLIER RUN                                                                                                                                                                                             
  !     IN 'ROUTP' IF NEEDED                                                                                                                                                                                                                                     
  !                                                                                                                                                                                                                                                              
        IF(DATA(20).EQ.'YES')THEN                                                                                                                                                                                                                                
        IF((IDAYR.GT.IRUN.AND.IYRR.EQ.IDATA(9)) &                                                                                                                                                                                                                
        .OR.IYRR.GT.IDATA(9))THEN                                                                                                                                                                                                                                
  !      WRITE(* 333)'ROUTP'                                                                                                                                                                                                                                     
        CALL ROUTP(NHW NHE,NVN,NVS)                                                                                                                                                                                                                              
        ENDIF                                                                                                                                                                                                                                                    
        ENDIF                                                                                                                                                                                                                                                    
        ENDIF                                                                                                                                                                                                                                                    
  !                                                                                                                                                                                                                                                              
  !     INITIALIZE ALL SOIL CHEMISTRY VARIABLES IN 'STARTE'                                                                                                                                                                                                      
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'STARTE'                                                                                                                                                                                                                                    
        CALL STARTE(NHW NHE,NVN,NVS)                                                                                                                                                                                                                             
  !                                                                                                                                                                                                                                                              
  !     BEGIN DAILY TIME STEP                                                                                                                                                                                                                                    
  !                                                                                                                                                                                                                                                              
  9000  I=IDAYR+1                                                                                                                                                                                                                                                
        IF(I.NE.LYRC.OR.NYR.NE.0)THEN                                                                                                                                                                                                                            
        IF(I.GT.LYRX.AND.NYR.NE.0)THEN                                                                                                                                                                                                                           
        I=I-LYRX                                                                                                                                                                                                                                                 
        IYRR=IYRR+1                                                                                                                                                                                                                                              
        ENDIF                                                                                                                                                                                                                                                    
        ENDIF                                                                                                                                                                                                                                                    
        IF(I.GT.IFIN)GO TO 9999                                                                                                                                                                                                                                  
  !      WRITE(* 333)'FINISH'                                                                                                                                                                                                                                    
  !                                                                                                                                                                                                                                                              
  !     UPDATE DAILY VARIABLES SUCH AS MANAGEMENT INPUTS                                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
        CALL DAY(I NHW,NHE,NVN,NVS)                                                                                                                                                                                                                              
        DO 9995 J=1 24                                                                                                                                                                                                                                           
  !                                                                                                                                                                                                                                                              
  !     UPDATE HOURLY VARIABLES IN 'HOUR1'                                                                                                                                                                                                                       
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'WTHR'                                                                                                                                                                                                                                      
        CALL WTHR(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                           
  !      WRITE(* 333)'HOUR1'                                                                                                                                                                                                                                     
  333   FORMAT(A8)                                                                                                                                                                                                                                               
        CALL HOUR1(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                          
  !                                                                                                                                                                                                                                                              
  !     CALCULATE SOIL ENERGY BALANCE  WATER AND HEAT FLUXES IN 'WATSUB'                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'WAT'                                                                                                                                                                                                                                       
        CALL WATSUB(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
  !     CALCULATE SOIL BIOLOGICAL TRANSFORMATIONS IN 'NITRO'                                                                                                                                                                                                     
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'NIT'                                                                                                                                                                                                                                       
        CALL NITRO(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                          
  !                                                                                                                                                                                                                                                              
  !     UPDATE PLANT PHENOLOGY IN 'HFUNC'                                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'HFUNC'                                                                                                                                                                                                                                     
        CALL HFUNC(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                          
  !                                                                                                                                                                                                                                                              
  !     CALCULATE CANOPY CO2 UPTAKE AT FULL TURGOR  CANOPY WATER POTENTIAL,                                                                                                                                                                                      
  !     HYDRAULIC AND STOMATAL RESISTANCES AND CANOPY ENERGY BALANCE IN 'UPTAKE'                                                                                                                                                                                 
  !     CALCULATE ROOT UPTAKE OF WATER  OXYGEN, NH4, NO3 AND PO4 IN 'UPTAKE'                                                                                                                                                                                     
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'UPTK'                                                                                                                                                                                                                                      
        CALL UPTAKE(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
  !     CALCULATE CANOPY CO2 UPTAKE AT AMBIENT TURGOR  AUTOTROPHIC AND GROWTH                                                                                                                                                                                    
  !     RESPIRATION  PLANT C ALLOCATION, CANOPY AND ROOT GROWTH IN 'GROSUB'                                                                                                                                                                                      
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'GRO'                                                                                                                                                                                                                                       
        CALL GROSUB(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
  !     CALCULATE ROOT-SOIL C AND NUTRIENT EXCHANGE FOR ALL PLANT SPECIES                                                                                                                                                                                        
  !     IN 'EXTRACT'                                                                                                                                                                                                                                             
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'EXTR'                                                                                                                                                                                                                                      
        CALL EXTRACT(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
  !     CALCULATE SOLUTE EQUILIBRIA IN 'SOLUTE'                                                                                                                                                                                                                  
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'SOL'                                                                                                                                                                                                                                       
        CALL SOLUTE(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
  !     CALCULATE GAS AND SOLUTE FLUXES IN 'TRNSFR'                                                                                                                                                                                                              
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'TRN'                                                                                                                                                                                                                                       
        CALL TRNSFR(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
  !     CALCULATE ADDITIONAL SOLUTE FLUXES IN 'TRNSFRS' IF SALT OPTION SELECTED                                                                                                                                                                                  
  !                                                                                                                                                                                                                                                              
        CALL TRNSFRS(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
  !     CALCULATE SOIL SEDIMENT TRANSPORT IN 'EROSION'                                                                                                                                                                                                           
  !                                                                                                                                                                                                                                                              
        CALL EROSION(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                        
  !                                                                                                                                                                                                                                                              
  !     UPDATE ALL SOIL STATE VARIABLES FOR WATER  HEAT, GAS, SOLUTE                                                                                                                                                                                             
  !     AND SEDIMENT FLUXES IN 'REDIST'                                                                                                                                                                                                                          
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'RED'                                                                                                                                                                                                                                       
        CALL REDIST(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                         
  !      WRITE(* 333)'END'                                                                                                                                                                                                                                       
  !                                                                                                                                                                                                                                                              
  !     WRITE HOURLY SOIL AND PLANT OUTPUT IN 'OUTSH' AND 'OUTPH'                                                                                                                                                                                                
  !                                                                                                                                                                                                                                                              
        IF((J/JOUT)*JOUT.EQ.J)THEN                                                                                                                                                                                                                               
  !      WRITE(* 333)'OUTSH'                                                                                                                                                                                                                                     
        CALL OUTSH(I J,NT,NE,NAX,NDX,NTX,NEX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                    
        CALL OUTPH(I J,NT,NE,NAX,NDX,NTX,NEX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                    
        ENDIF                                                                                                                                                                                                                                                    
  !                                                                                                                                                                                                                                                              
  !     WRITE OUTPUT FOR DYNAMIC VISUALIZATION                                                                                                                                                                                                                   
  !                                                                                                                                                                                                                                                              
        IF(DATA(18).EQ.'YES')THEN                                                                                                                                                                                                                                
        IF((J/JOUT)*JOUT.EQ.J)THEN                                                                                                                                                                                                                               
  !      WRITE(* 333)'VIS'                                                                                                                                                                                                                                       
        CALL VISUAL(I J,NHW,NHE,NVN,NVS)                                                                                                                                                                                                                         
        ENDIF                                                                                                                                                                                                                                                    
        ENDIF                                                                                                                                                                                                                                                    
  9995  CONTINUE                                                                                                                                                                                                                                                 
        IF(DATA(19).EQ.'YES'.AND.KOUT.GT.0)THEN                                                                                                                                                                                                                  
  !                                                                                                                                                                                                                                                              
  !     WRITE ALL SOIL AND PLANT STATE VARIABLES AND OTHER INFORMATION                                                                                                                                                                                           
  !     NEEDED TO RE-INITIALIZE THE MODEL TO CHECKPOINT FILES                                                                                                                                                                                                    
  !     IN 'WOUTS'  'WOUTP' AND 'WOUTQ'                                                                                                                                                                                                                          
  !                                                                                                                                                                                                                                                              
        IF((I/KOUT)*KOUT.EQ.I.OR.I.EQ.IFIN)THEN                                                                                                                                                                                                                  
  !      WRITE(* 333)'WOUTS'                                                                                                                                                                                                                                     
        CALL WOUTS(I NHW,NHE,NVN,NVS)                                                                                                                                                                                                                            
        CALL WOUTP(I NHW,NHE,NVN,NVS)                                                                                                                                                                                                                            
        CALL WOUTQ(I NHW,NHE,NVN,NVS)                                                                                                                                                                                                                            
        ENDIF                                                                                                                                                                                                                                                    
        ENDIF                                                                                                                                                                                                                                                    
  !                                                                                                                                                                                                                                                              
  !     WRITE DAILY SOIL AND PLANT OUTPUT IN 'OUTSD' AND 'OUTPD'                                                                                                                                                                                                 
  !                                                                                                                                                                                                                                                              
        IF((I/IOUT)*IOUT.EQ.I)THEN                                                                                                                                                                                                                               
  !      WRITE(* 333)'OUTSD'                                                                                                                                                                                                                                     
        CALL OUTSD(I NT,NE,NAX,NDX,NTX,NEX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                      
        CALL OUTPD(I NT,NE,NAX,NDX,NTX,NEX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                      
        ENDIF                                                                                                                                                                                                                                                    
  !                                                                                                                                                                                                                                                              
  !     PERFORM MASS AND ENERGY BALANCE CHECKS IN 'EXEC'                                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
  !      WRITE(* 333)'EXEC'                                                                                                                                                                                                                                      
        CALL EXEC(I)                                                                                                                                                                                                                                             
  !                                                                                                                                                                                                                                                              
  !     RE-INITIALIZE MODEL FROM CHECKPOINT FILES IF NEEDED                                                                                                                                                                                                      
  !                                                                                                                                                                                                                                                              
        IF(NYR.NE.1.AND.IDAYR.NE.IOLD)THEN                                                                                                                                                                                                                       
  !      WRITE(* 333)'REINIT'                                                                                                                                                                                                                                    
        CALL ROUTS(NHW NHE,NVN,NVS)                                                                                                                                                                                                                              
        CALL ROUTP(NHW NHE,NVN,NVS)                                                                                                                                                                                                                              
        ENDIF                                                                                                                                                                                                                                                    
        GO TO 9000                                                                                                                                                                                                                                               
  9999  CONTINUE                                                                                                                                                                                                                                                 
  !      WRITE(* 333)'LOOP'                                                                                                                                                                                                                                      
  !                                                                                                                                                                                                                                                              
  !     WRITE OUTPUT FILES FOR EACH GRID CELL IN 'SPLIT'                                                                                                                                                                                                         
  !                                                                                                                                                                                                                                                              
  #ifdef _WIN_                                                                                                                                                                                                                                                   
        CALL SPLIT(NT NE,NAX,NDX,NTX,NEX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                        
  #else                                                                                                                                                                                                                                                          
        CALL SPLITC(NT NE,NAX,NDX,NTX,NEX,NHW,NHE,NVN,NVS)                                                                                                                                                                                                       
  #endif                                                                                                                                                                                                                                                         
  !      WRITE(* 333)'SPLIT'                                                                                                                                                                                                                                     
        RETURN                                                                                                                                                                                                                                                   
        END                                                                                                                                                                                                                                                      
